### ISSUE TITLE
android 9.0圆形 带边框 图片内容 超出圆形边框

### ISSUE THREAD

**Issue by Marysays** [SheHuan/NiceImageView#6]
![1536169312264](https://user-images.githubusercontent.com/11965812/45110863-0b618d80-b176-11e8-920e-cfe371d99a28.jpg)
已经cover src

**Comment by liangpengfei** [comment]
同样遇到了这个问题。。

**Comment by Marysays** [comment]
大佬 这个什么时候能修 都两个月了。。。。。。。。。。

**Comment by SheHuan** [comment]
8.1到9.0的设备存在兼容性的问题，问题已经定位，只是目前缺少测试设备

**Comment by Marysays** [comment]
你as直接载个 9.0的虚拟机 我也是在虚拟机上面发现的bug

**Comment by zzhdroid1990** [comment]
能不能定位的问题发一下吧，我先在代码里面自己改一下

**Comment by Marysays** [comment]
作者更新太慢了。。Bug我只能自己动手修了（有没有影响到其他功能需要大家再认真测下 我试是没问题的~）
==========================分割线==============================
一、问题出在哪？
控件用到了 Xfermode这个东西，我试了下。
1、先画一个circle（非bitmap），然后setXfermode 为Src_In，再画一个bitmap(图片的)，正常显示。
2、先画一个bitmap(图片的)，然后setXfermode 为Dsr_In,再画circle。异常。（大概看下来代码 作者应该用的这一种画法）
=============================上代码======================
//替换掉NICEIAMGE类中的这个方法就行了
@Override
    protected void onDraw(Canvas canvas) {
        // 使用图形混合模式来显示指定区域的图片
        canvas.saveLayer(0,0,getWidth(),getHeight(),null,Canvas.ALL_SAVE_FLAG);
        paint.reset();
        path.reset();

        if (!isCoverSrc) {
            float sx = 1.0f * (width - 2 * borderWidth - 2 * innerBorderWidth) / width;
            float sy = 1.0f * (height - 2 * borderWidth - 2 * innerBorderWidth) / height;
            // 缩小画布，使图片内容不被border、padding覆盖
            canvas.scale(sx, sy, width / 2.0f, height / 2.0f);
        }

        if (isCircle) {
            path.addCircle(width / 2.0f, height / 2.0f, radius, Path.Direction.CCW);
        } else {
            path.addRoundRect(srcRectF, srcRadii, Path.Direction.CCW);
        }

        paint.setAntiAlias(true);
        paint.setStyle(Paint.Style.FILL);

        canvas.drawPath(path, paint);
        paint.setXfermode(xfermode);
        canvas.drawBitmap(drawableToBitamp(exChangeSize(getDrawable())), 0, 0, paint);
        paint.setXfermode(null);
        
        // 绘制遮罩
        if (maskColor != 0) {
            paint.setColor(maskColor);
            canvas.drawPath(path, paint);
        }
        // 恢复画布
        canvas.restore();
        // 绘制边框
        drawBorders(canvas);
    }

=================== drawableToBitamp方法===================

    private Bitmap drawableToBitamp(Drawable drawable)
    {
        if (drawable instanceof BitmapDrawable)
        {
            BitmapDrawable bd = (BitmapDrawable) drawable;
            return bd.getBitmap();
        }
        // 当设置不为图片，为颜色时，获取的drawable宽高会有问题，所有当为颜色时候获取控件的宽高
        int w = drawable.getIntrinsicWidth() <= 0 ? getWidth() : drawable.getIntrinsicWidth();
        int h = drawable.getIntrinsicHeight() <= 0 ? getHeight() : drawable.getIntrinsicHeight();
        Bitmap bitmap = Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bitmap);
        drawable.setBounds(0, 0, w, h);
        drawable.draw(canvas);
        return bitmap;
    }

======================exChangeSize===========
  private Drawable exChangeSize(Drawable drawable){
        float scale = 1.0f;
        scale = Math.max(getWidth() * 1.0f / drawable.getIntrinsicWidth(), getHeight()
                * 1.0f / drawable.getIntrinsicHeight());
        drawable.setBounds(0, 0, (int) (scale * drawable.getIntrinsicWidth()),
                (int) (scale * drawable.getIntrinsicHeight()));
        return drawable;
    }

==============end==================

fix: 9.0上显示异常问题。

**Comment by SheHuan** [comment]
问题已修复

**Comment by lvyandev** [comment]
诺基亚X6上还是发现同样的问题
版本1.0.5

![1](https://user-images.githubusercontent.com/18045999/49709171-0a0c9900-fc6e-11e8-8553-7e8e6de9e28a.gif)

**Comment by Marysays** [comment]
按照我那个思路看下 问题是出在这

**Comment by Gerry0927** [comment]
还有个问题就是 9.0系统中 设置了圆角度，但是在界面中展示的没有效果

**Comment by Maheaven** [comment]
9.0系统  列表中，来回滑动  圆形 有时候可以正常显示，有时候显示矩形。是不是drawCircleBorder方法里面drawPath时 也要判断if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.O_MR1)  进行适配

**Comment by idic779** [comment]
你好，华为手机9.0系统 设置了圆角度不生效，请问下是什么原因

**Comment by wsfbailebai** [comment]
小米8,9.0系统仍然存在这个问题

**Comment by YBill** [comment]
https://github.com/YBill/ShapedImageView

**Comment by clgg** [comment]
super.onDraw(canvas);
        paint.reset();
        path.reset();
 后面增加这句srcRectF .reset(); 试下
